# Generated by Django 2.0 on 2019-11-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_auto_20191121_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDonHang', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=200)),
                ('DanhSachMaSanPham', models.CharField(max_length=200)),
                ('DanhSachTenSanPham', models.CharField(max_length=200)),
                ('TongSoLuong', models.IntegerField(default=0)),
                ('TongTien', models.IntegerField(default=0)),
                ('NgayMua', models.DateTimeField(verbose_name='date published')),
                ('DiaChi', models.CharField(max_length=200)),
                ('SoDienThoai', models.IntegerField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('TinhTrangDonHang', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('MaSanPham', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=200)),
                ('GiaDaGiam', models.IntegerField(default=0)),
                ('GiaBan', models.IntegerField(default=0)),
                ('Soluong', models.IntegerField(default=0)),
                ('NhaCungCap', models.CharField(max_length=200)),
                ('MaLoai', models.CharField(max_length=200)),
                ('HinhAnh', models.CharField(max_length=200)),
                ('SoluongNhap', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaLoai', models.CharField(max_length=200)),
                ('TenLoai', models.CharField(max_length=200)),
                ('NhaCungCap', models.CharField(max_length=200)),
                ('MoTa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNhaCungCap', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('TenNhaCungCap', models.CharField(max_length=200)),
                ('DiaChi', models.CharField(max_length=200)),
                ('SoDienThoai', models.CharField(max_length=200)),
                ('LoGo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatKhau', models.CharField(max_length=200)),
                ('TenTaiKhoang', models.CharField(max_length=200)),
                ('Gioitinh', models.CharField(max_length=200)),
                ('SoDienThoai', models.IntegerField(default=0)),
                ('Email', models.CharField(max_length=200)),
                ('NgaySinh', models.DateTimeField(verbose_name='date published')),
                ('DiaChi', models.CharField(max_length=200)),
                ('SoLuotMua', models.CharField(max_length=200)),
                ('Role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinSanPham',
            fields=[
                ('MaSanPham', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('MoTa', models.CharField(max_length=200)),
                ('HinhAnhChiTiet', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
