# Generated by Django 2.0 on 2019-11-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191121_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='SoDienThoai',
        ),
    ]
