# Generated by Django 2.2.8 on 2019-12-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_donhang_sodienthoai'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSanPham', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=200)),
                ('GiaDaGiam', models.IntegerField(default=0)),
                ('GiaBan', models.IntegerField(default=0)),
                ('Soluong', models.IntegerField(default=0)),
                ('NhaCungCap', models.CharField(max_length=200)),
                ('MaLoai', models.CharField(max_length=200)),
                ('HinhAnh', models.CharField(max_length=200)),
                ('SoluongNhap', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='LoaiSanPham1',
        ),
        migrations.RenameField(
            model_name='loaisanpham',
            old_name='HinhAnh',
            new_name='MaNhaCungCap',
        ),
        migrations.RenameField(
            model_name='loaisanpham',
            old_name='NhaCungCap',
            new_name='MoTa',
        ),
        migrations.RenameField(
            model_name='loaisanpham',
            old_name='SoluongNhap',
            new_name='TenLoai',
        ),
        migrations.RemoveField(
            model_name='loaisanpham',
            name='GiaBan',
        ),
        migrations.RemoveField(
            model_name='loaisanpham',
            name='GiaDaGiam',
        ),
        migrations.RemoveField(
            model_name='loaisanpham',
            name='MaSanPham',
        ),
        migrations.RemoveField(
            model_name='loaisanpham',
            name='Soluong',
        ),
        migrations.RemoveField(
            model_name='loaisanpham',
            name='Ten',
        ),
        migrations.RemoveField(
            model_name='taikhoang',
            name='id',
        ),
        migrations.AlterField(
            model_name='loaisanpham',
            name='MaLoai',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taikhoang',
            name='TenTaiKhoang',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
